### ISSUE TITLE
Global variables not seen by Functions

### ISSUE THREAD

**Issue by DanieleBenedettelli** [iCheh/Clev3r-1#1]
Hello.
Thanks for your useful IDE. I found it by chance and I love it! 
I am using version 1.6.8.9, and I found a bug (or an intended feature).
If I declare a **global variable, and try to read it from within a Function**, the preprocessor returns this error:
code: 1405 ===> Variable not defined 
**This problem doesn't arise when reading global variables inside a Sub.**

I am not sure if this is by design (a Function can be declared in an import), but it's still annoying.
For example, I want to declare globally the ports the motors are atteched to, and then read them everywhere in the program.
This is a very bad habit, so I understand if you designed things like that.

**Comment by DanieleBenedettelli** [comment]
I see now that I should have used the @ operator.

**Comment by iCheh** [comment]
Добрый день!
Глобальные переменные не доступны внутри функций в том виде, как это есть в процедурах (Sub).
Для доступа к такой переменной внутри функции нужно добавить к ней символ @

myVar = 10

Function Test()

    curVar = @myVar

EndFunction
